import numpy as np
import matplotlib.pyplot as plt

(rp_c, Sig_a_11) = np.loadtxt('./txtfiles/SigIA_a_sigz=0.11.txt', unpack=True)
(rp_c, Sig_a_9) = np.loadtxt('./txtfiles/SigIA_a_sigz=0.09.txt', unpack=True)
(rp_c, Sig_a_7) = np.loadtxt('./txtfiles/SigIA_a_sigz=0.07.txt', unpack=True)
(rp_c, Sig_a_5) = np.loadtxt('./txtfiles/SigIA_a_sigz=0.05.txt', unpack=True)


plt.figure()
plt.loglog(rp_c, Sig_a_11, 'g+', label='$\sigma_z$=0.11')
plt.hold(True)
plt.loglog(rp_c, Sig_a_9, 'm+', label='$\sigma_z$=0.09')
plt.hold(True)
plt.loglog(rp_c, Sig_a_7, 'b+', label='$\sigma_z$=0.07')
plt.hold(True)
plt.loglog(rp_c, Sig_a_5, 'k+', label='$\sigma_z$=0.05')
plt.legend()
plt.xlabel('$r_p$, Mpc/h')
plt.ylabel('$\langle \Sigma_{\\rm IA} \\rangle$')
plt.ylim(8000, 15000)
plt.title('Sample a, $z_l<z<z_l+\Delta z$')
plt.savefig('./plots/SigIA_wrt_sigz_a.pdf')
plt.close()

(rp_c, Sig_b_11) = np.loadtxt('./txtfiles/SigIA_b_sigz=0.11.txt', unpack=True)
(rp_c, Sig_b_9) = np.loadtxt('./txtfiles/SigIA_b_sigz=0.09.txt', unpack=True)
(rp_c, Sig_b_7) = np.loadtxt('./txtfiles/SigIA_b_sigz=0.07.txt', unpack=True)
(rp_c, Sig_b_5) = np.loadtxt('./txtfiles/SigIA_b_sigz=0.05.txt', unpack=True)

plt.figure()
plt.loglog(rp_c, Sig_b_11, 'g+', label='$\sigma_z$=0.11')
plt.hold(True)
plt.loglog(rp_c, Sig_b_9, 'm+', label='$\sigma_z$=0.09')
plt.hold(True)
plt.loglog(rp_c, Sig_b_7, 'b+', label='$\sigma_z$=0.07')
plt.hold(True)
plt.loglog(rp_c, Sig_b_5, 'k+', label='$\sigma_z$=0.05')
plt.legend()
plt.xlabel('$r_p$, Mpc/h')
plt.ylabel('$\langle \Sigma_{\\rm IA} \\rangle$')
plt.ylim(3000, 11000)
plt.title('Sample b, $z>z_l+\Delta z$')
plt.savefig('./plots/SigIA_wrt_sigz_b.pdf')
plt.close()
