import numpy as np
import matplotlib.pyplot as plt

(k11, Pk_11) = np.loadtxt('../txtfiles/1halo_and_halofit_Pk_z=0.32_M1e11_newexp.dat', unpack=True)
(k12, Pk_12) = np.loadtxt('../txtfiles/1halo_and_halofit_Pk_z=0.32_M1e12_newexp.dat', unpack=True)
(k13, Pk_13) = np.loadtxt('../txtfiles/1halo_and_halofit_Pk_z=0.32_M1e13_newexp.dat', unpack=True)
(k14, Pk_14) = np.loadtxt('../txtfiles/1halo_and_halofit_Pk_z=0.32_M1e14_newexp.dat', unpack=True)
(k15, Pk_15) = np.loadtxt('../txtfiles/1halo_and_halofit_Pk_z=0.32_M1e15_newexp.dat', unpack=True)
(kHF, Pk_HF) = np.loadtxt('../txtfiles/NL_kmax4000_z=0.32.dat', unpack =True)

plt.figure()
plt.loglog(k11, Pk_11,label='M=1e11')
plt.hold(True)
plt.loglog(k12, Pk_12, label='M=1e12')
plt.hold(True)
plt.loglog(k13, Pk_13, label='M=1e13')
plt.hold(True)
plt.loglog(k14, Pk_14, label='M=1e14')
plt.hold(True)
plt.loglog(k15, Pk_15, label='M=1e15')
plt.hold(True)
plt.loglog(kHF, Pk_HF, label='HaloFit')
plt.xlim(10**(-4), 100.)
plt.ylim(10**(-2), 5.*10**6)
plt.xlabel('$k$')
plt.ylabel('$P(k)$')
plt.legend()
plt.savefig('../plots/Pk_various_masses_newexp.png')
plt.close()
